UserParameter=proxmox.api,/usr/bin/sudo -n /usr/local/lib/zabbix-proxmox/bin/proxmox-api
UserParameter=proxmox.journal,/usr/bin/sudo -n /usr/local/lib/zabbix-proxmox/bin/proxmox-journal
UserParameter=proxmox.smart,/usr/bin/sudo -n /usr/local/lib/zabbix-proxmox/bin/proxmox-smart
UserParameter=proxmox.zfs,/usr/bin/sudo -n /usr/local/lib/zabbix-proxmox/bin/proxmox-zfs
UserParameter=proxmox.backup,/usr/bin/sudo -n /usr/local/lib/zabbix-proxmox/bin/proxmox-backup
UserParameter=proxmox.updates,/usr/bin/sudo -n /usr/local/lib/zabbix-proxmox/bin/proxmox-updates
UserParameter=proxmox.services,/usr/bin/sudo -n /usr/local/lib/zabbix-proxmox/bin/proxmox-services
UserParameter=proxmox.certificates,/usr/bin/sudo -n /usr/local/lib/zabbix-proxmox/bin/proxmox-certificates
UserParameter=proxmox.storage,/usr/bin/sudo -n /usr/local/lib/zabbix-proxmox/bin/proxmox-storage