UserParameter=proxmox.api,python3 /usr/local/lib/zabbix-proxmox/src/proxmox_agent.py api
UserParameter=proxmox.journal,python3 /usr/local/lib/zabbix-proxmox/src/proxmox_agent.py journal
UserParameter=proxmox.smart,python3 /usr/local/lib/zabbix-proxmox/src/proxmox_agent.py smart
UserParameter=proxmox.zfs,python3 /usr/local/lib/zabbix-proxmox/src/proxmox_agent.py zfs
UserParameter=proxmox.backup,python3 /usr/local/lib/zabbix-proxmox/src/proxmox_agent.py backup
UserParameter=proxmox.updates,python3 /usr/local/lib/zabbix-proxmox/src/proxmox_agent.py updates
UserParameter=proxmox.services,python3 /usr/local/lib/zabbix-proxmox/src/proxmox_agent.py services
UserParameter=proxmox.certificates,python3 /usr/local/lib/zabbix-proxmox/src/proxmox_agent.py certificates
UserParameter=proxmox.storage,python3 /usr/local/lib/zabbix-proxmox/src/proxmox_agent.py storage